apiVersion: batch/v1
kind: CronJob
metadata:
  name: planter
spec:
  schedule: "59 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          # This node is the only node with the FTDI device
          nodeName: nas
          restartPolicy: Never
          containers:
            - name: planter
              image: "ijmacd/planter:1.1.0"
              command: ["python", "run.py"]
              args: ["$(FLOW_DURATION)"]
              envFrom:
                - configMapRef:
                    name: planter-config
              volumeMounts:
                - mountPath: /dev/bus/usb
                  name: usb-dev
              securityContext:
                privileged: true
              resources:
                requests:
                  cpu: 10m
                  memory: 10Mi
                limits:
                  memory: 10Mi
          volumes:
            - name: usb-dev
              hostPath:
                path: /dev/bus/usb
                type: Directory
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "planter-config"
data:
  FLOW_DURATION: "5"
